@Api_HostAddress = http://localhost:5174

GET {{Api_HostAddress}}/todos/
Accept: application/json

###

POST {{Api_HostAddress}}/todos/
Content-Type: application/json

{
    "Title": "Something to do",
    "Description": "A very important description about what we are going to do",
    "IsComplete": false
}